version: "3.8"
services:
  lua-script-assets:
    build:
      context: .
      dockerfile: Dockerfile
    image: 2kpixelstudios/lua-script-assets
    container_name: lua-script-assets
    command: [ "/src/scripts/package-instructions.sh" ]
    environment:
     - AWS_ACCESS_KEY_ID # NOTE: This name MUST be AWS_ACCESS_KEY_ID for AWS CLI to work
     - AWS_SECRET_ACCESS_KEY # NOTE: This name MUST be AWS_SECRET_ACCESS_KEY for AWS CLI to work
     - AWS_DEFAULT_REGION
     - AWS_OUTPUT_TYPE
     - PS2K_SECRET_SSH_KEY_ID
    volumes:
      - type: bind
        source: $HOST_DIR/scripts/packaging
        target: /unity-project/packaging
