version: "3.8"
services:
  lua-script-assets-packager:
    build:
      context: .
      dockerfile: Dockerfile-packager
    image: cometpeakgames/lua-script-assets-packager
    container_name: lua-script-assets-packager
    command: [ "/src/scripts/package-instructions.sh" ]
    environment:
     - AWS_ACCESS_KEY_ID # NOTE: This name MUST be AWS_ACCESS_KEY_ID for AWS CLI to work
     - AWS_SECRET_ACCESS_KEY # NOTE: This name MUST be AWS_SECRET_ACCESS_KEY for AWS CLI to work
     - AWS_DEFAULT_REGION
     - AWS_OUTPUT_TYPE
     - CPG_SECRET_SSH_KEY_ID
    volumes:
      - type: bind
        source: $HOST_DIR/scripts/packaging
        target: /unity-project-packager/packaging
