version: "3.8"
services:
  lua-script-assets:
    build:
      context: .
      dockerfile: Dockerfile
    image: 2kpixelstudios/lua-script-assets
    container_name: lua-script-assets
    environment:
      - PS2K_CICD_EMAIL
      - PS2K_CICD_NAME
      - GIT_REMOTE_URL=git@github.com:2kpixelstudios/lua-script-assets.git

